const API="/api",$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const SP=["setosa","versicolor","virginica"],CL={setosa:"#10b981",versicolor:"#8b5cf6",virginica:"#f97316"};
const F=["sepal_length","sepal_width","petal_length","petal_width"],FL=["Sepal Length","Sepal Width","Petal Length","Petal Width"];
const SAMPLES=[{sepal_length:5.1,sepal_width:3.5,petal_length:1.4,petal_width:.2},{sepal_length:4.9,sepal_width:3,petal_length:1.4,petal_width:.2},{sepal_length:7,sepal_width:3.2,petal_length:4.7,petal_width:1.4},{sepal_length:6.4,sepal_width:3.2,petal_length:4.5,petal_width:1.5},{sepal_length:6.3,sepal_width:3.3,petal_length:6,petal_width:2.5},{sepal_length:5.8,sepal_width:2.7,petal_length:5.1,petal_width:1.9},{sepal_length:5,sepal_width:3.4,petal_length:1.5,petal_width:.2},{sepal_length:6.1,sepal_width:2.8,petal_length:4.7,petal_width:1.2},{sepal_length:7.6,sepal_width:3,petal_length:6.6,petal_width:2.1}];

function toast(m,t){const e=document.createElement("div");e.className="toast "+t;e.textContent=m;$("#toast-container").appendChild(e);setTimeout(()=>e.remove(),3000)}
async function api(u,o){try{const r=await fetch(u,o||{});if(!r.ok)throw new Error("Server error: "+r.status);return await r.json()}catch(e){toast("API Error: "+e.message,"error");return null}}

$$(".tab-btn").forEach(b=>b.addEventListener("click",()=>{$$(".tab-btn").forEach(x=>x.classList.remove("active"));$$(".tab-content").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(`#panel-${b.dataset.tab}`).classList.add("active")}));

$("#predict-form").addEventListener("submit",async e=>{e.preventDefault();const d={};F.forEach(f=>d[f]=parseFloat($(`#${f}`).value));const b=$("#predict-btn");b.disabled=true;b.innerHTML='<span class="spinner"></span> Classifying...';const r=await api(API+"/predict",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});b.disabled=false;b.textContent="✨ Classify";if(!r||r.error)return toast(r?r.error:"Prediction failed","error");showResult(r,d);toast("Predicted: "+r.predicted_species,"success")});

function showResult(r,inp){$("#result-placeholder").style.display="none";$("#result-content").classList.remove("hidden");const s=r.predicted_species;$("#result-species-name").textContent=s;$("#result-species-name").style.color=CL[s]||"#1e1b4b";$("#result-model-badge").textContent="Model: "+r.model_used;const pd=$("#probabilities");pd.innerHTML=SP.map(x=>{const p=(r.probabilities&&r.probabilities[x])||0;return`<div class="prob-row"><span class="prob-label">${x}</span><div class="prob-bar-bg"><div class="prob-bar-fill ${x}" style="width:0%"></div></div><span class="prob-value">${p.toFixed(1)}%</span></div>`}).join("");setTimeout(()=>SP.forEach(x=>{const p=(r.probabilities&&r.probabilities[x])||0;const b=pd.querySelector(`.prob-bar-fill.${x}`);if(b)b.style.width=p+"%"}),50);$("#result-features").innerHTML='<div class="feat-grid">'+F.map((f,i)=>`<div class="feat-item"><span class="feat-name">${FL[i]}</span><span class="feat-val">${inp[f]} cm</span></div>`).join("")+"</div>"}

$("#random-btn").addEventListener("click",()=>{const s=SAMPLES[Math.floor(Math.random()*SAMPLES.length)];F.forEach(f=>$(`#${f}`).value=s[f]);toast("Random sample loaded","info")});

async function loadMetrics(){const m=await api(API+"/metrics");if(!m)return;$("#metrics-overview").innerHTML=[["best_accuracy",m.best_accuracy+"%","Best Accuracy"],["samples",m.dataset_info.total_samples,"Samples"],["feats",m.dataset_info.num_features,"Features"],["models",Object.keys(m.all_results).length,"Models Trained"]].map(x=>`<div class="summary-card"><div class="value">${x[1]}</div><div class="label">${x[2]}</div></div>`).join("");const d=$("#metrics-details");d.innerHTML="";for(const n in m.all_results){const v=m.all_results[n],b=n===m.best_model;d.innerHTML+=`<div class="model-card${b?" best":""}">${b?'<span class="best-label">Best</span>':""}<h4>${n}</h4><div class="model-stat"><span class="s-label">Accuracy</span><span class="s-value">${v.accuracy}%</span></div><div class="model-stat"><span class="s-label">CV Mean</span><span class="s-value">${v.cv_mean}%</span></div><div class="model-stat"><span class="s-label">CV Std</span><span class="s-value">+/- ${v.cv_std}%</span></div></div>`}const bd=m.all_results[m.best_model];if(bd&&bd.confusion_matrix)renderCM(bd.confusion_matrix,m.target_names)}

function renderCM(cm,l){let h='<div class="confusion-grid"><div class="cm-header"></div>'+l.map(x=>`<div class="cm-header">${x}</div>`).join("");cm.forEach((r,i)=>{h+=`<div class="cm-row-label">${l[i]}</div>`;r.forEach((v,j)=>h+=`<div class="cm-cell ${i===j?"diagonal":"off-diagonal"}">${v}</div>`)});$("#confusion-matrix").innerHTML=h+"</div>"}

let ds=[];
async function loadDataset(){const d=await api(API+"/dataset");if(!d)return;ds=d;renderTable(d)}
async function loadStats(){const s=await api(API+"/dataset/stats");if(!s)return;const ft=["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"],sn=["Sepal L.","Sepal W.","Petal L.","Petal W."];const c=$("#explore-stats");c.innerHTML="";for(const sp in s){const d=s[sp];c.innerHTML+=`<div class="species-card ${sp}"><h4>${sp}</h4><div class="stat-row"><span class="stat-name">Count</span><span class="stat-val">${d.count}</span></div>${ft.map((f,i)=>`<div class="stat-row"><span class="stat-name">${sn[i]}</span><span class="stat-val">${d.mean[f]} +/- ${d.std[f]}</span></div>`).join("")}</div>`}}
function renderTable(d){$("#data-tbody").innerHTML=d.map((r,i)=>`<tr><td>${i+1}</td><td>${r.sepal_length}</td><td>${r.sepal_width}</td><td>${r.petal_length}</td><td>${r.petal_width}</td><td><span class="species-tag ${r.species}">${r.species}</span></td></tr>`).join("")}
$$(".filter-btn").forEach(b=>b.addEventListener("click",()=>{$$(".filter-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");const f=b.dataset.filter;renderTable(f==="all"?ds:ds.filter(r=>r.species===f))}));

document.addEventListener("DOMContentLoaded",()=>{loadMetrics();loadDataset();loadStats()});
